name: 0 - Create Pull Request to Main

on:
  push:
    branches-ignore:
      - main
      - dev
      - stg
      - draft/**

jobs:
  create-pr-main:
    runs-on: ubuntu-latest
    steps:
      - name: ðŸ“¥ Checkout Repo
        uses: actions/checkout@v5
        with:
          fetch-depth: 1

      - name: ðŸ”„ Fetch Branches
        run: |
          git fetch origin main
          git fetch origin ${{ github.ref_name }} --unshallow

      - name: ðŸš— Create PR
        run: |
          if ! OUTPUT=$(gh pr create \
              --repo "${{ github.repository }}" \
              --base main \
              --head "${{ github.ref_name }}" \
              --title "PR automatic from ${{ github.ref_name }} to main" \
              --fill-verbose \
              --assignee "${{ github.actor }}" \
              --reviewer "${{ github.actor }}" 2>&1); then
          
              if echo "$OUTPUT" | grep -q "No commits between main and"; then
                echo "::warning::Could not create PR: no new commits between main and ${{ github.ref_name }}."
              elif echo "$OUTPUT" | grep -q "pull request for branch.*already exists"; then
                echo "::warning::PR already exists from ${{ github.ref_name }} to main: $(echo "$OUTPUT" | grep 'https://github.com')"
              else
                echo "$OUTPUT"
                exit 1
              fi
          else
            echo "$OUTPUT"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
