name: 0 - Create Pull Request to Main

on:
  push:
    branches-ignore:
      - main
      - dev
      - stg
      - draft/**

jobs:
  create-pr-main:
    runs-on: ubuntu-latest
    steps:
      - name: üì• Checkout Repo
        uses: actions/checkout@v5

      - name: üöó Create PR
        run: |
          if ! OUTPUT=$(gh pr create \
              --repo "$GITHUB_REPOSITORY" \
              --base main \
              --head "${{ github.ref_name }}" \
              --title "PR automatic from ${{ github.ref_name }} to main" \
              --fill-verbose \
              --assignee "${{ github.actor }}" \
              --reviewer "${{ github.actor }}" 2>&1); then
          
              if echo "$OUTPUT" | grep -q "No commits between main and"; then
                echo "::warning::N√£o foi poss√≠vel criar PR: nenhum commit novo entre main e ${{ github.ref_name }}."
              else
                echo "$OUTPUT"
                exit 1
              fi
          else
            echo "$OUTPUT"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
